use std::path::{Path, PathBuf};
use std::fs;

#[allow(dead_code)]
pub struct DocGenerator {
    project_root: PathBuf,
}

#[allow(dead_code)]
impl DocGenerator {
    pub fn new(project_root: PathBuf) -> Self {
        Self { project_root }
    }

    pub fn generate(&self, open: bool) -> Result<(), String> {
        println!("   Generating documentation for project");

        let output_dir = self.project_root.join("target/doc");
        fs::create_dir_all(&output_dir).map_err(|e| e.to_string())?;

        // 1. Scan for source files
        let mut source_files = Vec::new();
        self.collect_nyx_files(&self.project_root.join("src"), &mut source_files)?;

        // 2. Parse doc comments (simple regex approach for now)
        for _file in source_files {
            // let content = fs::read_to_string(&file).map_err(|e| e.to_string())?;
            // parse_docs(&content);
        }

        // 3. Generate HTML
        let index_html = r#"<!DOCTYPE html>
<html>
<head>
    <title>Nyx Documentation</title>
    <style>
        body { font-family: sans-serif; background: #1a1a1a; color: #eee; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #5fb8ff; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Project Documentation</h1>
        <p>Generated by NyxDoc</p>
    </div>
</body>
</html>"#;

        fs::write(output_dir.join("index.html"), index_html).map_err(|e| e.to_string())?;

        println!("    Finished generating docs at {}", output_dir.display());

        if open {
            println!("     Opening documentation in browser...");
        }

        Ok(())
    }

    fn collect_nyx_files(&self, dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
        if !dir.exists() { return Ok(()); }
        for entry in fs::read_dir(dir).map_err(|e| e.to_string())? {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if path.is_dir() {
                self.collect_nyx_files(&path, files)?;
            } else if path.extension().and_then(|s| s.to_str()) == Some("nyx") {
                files.push(path);
            }
        }
        Ok(())
    }
}
