//! Public API Interfaces Module
//!
//! Defines the public interfaces for the Nyx compiler's core subsystems.
//! These traits provide stable APIs for interacting with the compiler,
//! runtime, engines, and module systems.

use std::collections::HashMap;
use std::path::PathBuf;

use crate::core::diagnostics::{codes, ErrorCategory, NyxError};

/// Version information for interfaces
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize)]
pub struct Version {
    /// Major version number
    pub major: u16,
    /// Minor version number
    pub minor: u16,
    /// Patch version number
    pub patch: u16,
}

impl Default for Version {
    fn default() -> Self {
        Self {
            major: 0,
            minor: 1,
            patch: 0,
        }
    }
}

impl std::fmt::Display for Version {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

impl std::str::FromStr for Version {
    type Err = NyxError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let parts: Vec<&str> = s.split('.').collect();
        if parts.len() != 3 {
            return Err(NyxError::new(
                codes::INTERNAL_UNKNOWN_ERROR,
                "Invalid version format: expected major.minor.patch",
                ErrorCategory::Internal,
            ));
        }

        let major = parts[0]
            .parse()
            .map_err(|_| NyxError::new(codes::INTERNAL_UNKNOWN_ERROR, "Invalid major version", ErrorCategory::Internal))?;
        let minor = parts[1]
            .parse()
            .map_err(|_| NyxError::new(codes::INTERNAL_UNKNOWN_ERROR, "Invalid minor version", ErrorCategory::Internal))?;
        let patch = parts[2]
            .parse()
            .map_err(|_| NyxError::new(codes::INTERNAL_UNKNOWN_ERROR, "Invalid patch version", ErrorCategory::Internal))?;

        Ok(Self { major, minor, patch })
    }
}

// ============================================================================
// Compilation Unit and Related Types
// ============================================================================

/// Represents a compiled unit of code
#[derive(Debug, Clone)]
pub struct CompilationUnit {
    /// Unique identifier for the compilation unit
    pub id: String,
    /// Generated bytecode
    pub bytecode: Bytecode,
    /// Compilation warnings
    pub warnings: Vec<CompilationWarning>,
    /// Metadata about the compilation
    pub metadata: HashMap<String, String>,
}

impl CompilationUnit {
    /// Create a new compilation unit
    pub fn new(id: String, bytecode: Bytecode) -> Self {
        Self {
            id,
            bytecode,
            warnings: Vec::new(),
            metadata: HashMap::new(),
        }
    }
}

/// Compilation warning
#[derive(Debug, Clone)]
pub struct CompilationWarning {
    /// Warning code
    pub code: String,
    /// Warning message
    pub message: String,
    /// Source location
    pub location: SourceLocation,
}

/// Source location in code
#[derive(Debug, Clone)]
pub struct SourceLocation {
    /// File path
    pub file: PathBuf,
    /// Line number (1-indexed)
    pub line: u32,
    /// Column number (1-indexed)
    pub column: u32,
}

/// Bytecode representation
#[derive(Debug, Clone)]
pub struct Bytecode {
    /// Raw bytecode data
    pub data: Vec<u8>,
    /// Bytecode format version
    pub version: Version,
    /// Target architecture
    pub target: String,
}

/// Type check result
#[derive(Debug, Clone)]
pub struct TypeCheckResult {
    /// Whether type checking passed
    pub success: bool,
    /// Type errors found
    pub errors: Vec<TypeError>,
    /// Type warnings
    pub warnings: Vec<CompilationWarning>,
    /// Inferred type information
    pub type_info: HashMap<String, TypeInfo>,
}

/// Type error
#[derive(Debug, Clone)]
pub struct TypeError {
    /// Error code
    pub code: String,
    /// Error message
    pub message: String,
    /// Source location
    pub location: SourceLocation,
}

/// Type information
#[derive(Debug, Clone)]
pub struct TypeInfo {
    /// Type name
    pub name: String,
    /// Type kind
    pub kind: TypeKind,
}

/// Type kind
#[derive(Debug, Clone)]
pub enum TypeKind {
    /// Primitive type
    Primitive(PrimitiveType),
    /// Function type
    Function(Vec<TypeInfo>, Box<TypeInfo>),
    /// Array type
    Array(Box<TypeInfo>, Option<usize>),
    /// Struct type
    Struct(HashMap<String, TypeInfo>),
    /// Enum type
    Enum(Vec<(String, Vec<TypeInfo>)>),
    /// Unknown type
    Unknown,
}

/// Primitive types
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrimitiveType {
    /// 8-bit signed integer
    I8,
    /// 16-bit signed integer
    I16,
    /// 32-bit signed integer
    I32,
    /// 64-bit signed integer
    I64,
    /// 8-bit unsigned integer
    U8,
    /// 16-bit unsigned integer
    U16,
    /// 32-bit unsigned integer
    U32,
    /// 64-bit unsigned integer
    U64,
    /// 32-bit floating point
    F32,
    /// 64-bit floating point
    F64,
    /// Boolean
    Bool,
    /// Character
    Char,
    /// String
    String,
    /// Unit type (void)
    Unit,
}

// ============================================================================
// Runtime Types
// ============================================================================

/// Runtime value
#[derive(Debug, Clone)]
pub struct Value {
    /// Value type
    pub type_info: TypeInfo,
    /// Value data
    pub data: ValueData,
}

/// Value data
#[derive(Debug, Clone)]
pub enum ValueData {
    /// Integer value
    Integer(i64),
    /// Floating point value
    Float(f64),
    /// Boolean value
    Boolean(bool),
    /// String value
    String(String),
    /// Array value
    Array(Vec<Value>),
    /// Function value
    Function(FunctionHandle),
    /// Object value
    Object(HashMap<String, Value>),
    /// Null value
    Null,
    /// Undefined value
    Undefined,
}

/// Function handle
#[derive(Debug, Clone)]
pub struct FunctionHandle(pub u64);

/// Sandbox configuration
#[derive(Debug, Clone)]
pub struct SandboxConfig {
    /// Maximum memory in bytes
    pub max_memory: Option<usize>,
    /// Maximum CPU time in milliseconds
    pub max_cpu_time: Option<u64>,
    /// Maximum stack size in bytes
    pub max_stack_size: Option<usize>,
    /// Allowed network access
    pub allow_network: bool,
    /// Allowed file system access
    pub allow_file_system: bool,
    /// Environment variables to whitelist
    pub allowed_env_vars: Vec<String>,
}

impl Default for SandboxConfig {
    fn default() -> Self {
        Self {
            max_memory: Some(256 * 1024 * 1024), // 256 MB
            max_cpu_time: Some(5000), // 5 seconds
            max_stack_size: Some(8 * 1024 * 1024), // 8 MB
            allow_network: false,
            allow_file_system: false,
            allowed_env_vars: Vec::new(),
        }
    }
}

/// Sandbox for isolated execution
#[derive(Debug)]
pub struct Sandbox {
    /// Sandbox ID
    pub id: String,
    /// Configuration
    pub config: SandboxConfig,
    /// Whether the sandbox is active
    pub active: bool,
}

// ============================================================================
// Engine Types
// ============================================================================

/// Engine handle for loaded engines
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EngineHandle(pub u64);

/// Engine capabilities
#[derive(Debug, Clone)]
pub struct Capabilities {
    /// Supported language features
    pub features: Vec<String>,
    /// Supported target platforms
    pub targets: Vec<String>,
    /// Maximum optimization level
    pub max_optimization_level: u8,
    /// Whether concurrent compilation is supported
    pub concurrent_compilation: bool,
    /// Additional capabilities
    pub extra: HashMap<String, String>,
}

impl Default for Capabilities {
    fn default() -> Self {
        Self {
            features: Vec::new(),
            targets: vec!["x86_64".to_string(), "aarch64".to_string()],
            max_optimization_level: 3,
            concurrent_compilation: true,
            extra: HashMap::new(),
        }
    }
}

/// Engine configuration
#[derive(Debug, Clone, Deserialize)]
pub struct EngineConfig {
    /// Engine name
    pub name: String,
    /// Engine version
    pub version: Version,
    /// Configuration parameters
    pub parameters: HashMap<String, String>,
    /// Enabled features
    pub features: Vec<String>,
}

impl EngineConfig {
    /// Create a new engine configuration
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: Version::default(),
            parameters: HashMap::new(),
            features: Vec::new(),
        }
    }

    /// Add a feature
    pub fn with_feature(mut self, feature: impl Into<String>) -> Self {
        self.features.push(feature.into());
        self
    }

    /// Add a parameter
    pub fn with_param(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.parameters.insert(key.into(), value.into());
        self
    }
}

// ============================================================================
// Module Types
// ============================================================================

/// Module identifier
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ModuleId(pub u64);

/// Symbol information
#[derive(Debug, Clone)]
pub struct Symbol {
    /// Symbol name
    pub name: String,
    /// Symbol kind
    pub kind: SymbolKind,
    /// Symbol visibility
    pub visibility: Visibility,
    /// Symbol type
    pub symbol_type: TypeInfo,
}

/// Symbol kind
#[derive(Debug, Clone)]
pub enum SymbolKind {
    /// Function
    Function,
    /// Variable
    Variable,
    /// Constant
    Constant,
    /// Type
    Type,
    /// Module
    Module,
}

/// Symbol visibility
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Visibility {
    /// Public (exported)
    Public,
    /// Private to module
    Private,
    /// Internal (within crate/package)
    Internal,
}

// ============================================================================
// Public API Traits
// ============================================================================

/// CompilerAPI - Public compiler interface
///
/// This trait provides the public API for compiling source code.
/// Implementations provide different compilation strategies and backends.
pub trait CompilerAPI {
    /// Compile source code into a compilation unit
    fn compile(&mut self, source: &str) -> Result<CompilationUnit, NyxError>;

    /// Type check source code without generating output
    fn check(&mut self, source: &str) -> Result<TypeCheckResult, NyxError>;

    /// Get the compiler version
    fn get_version(&self) -> Version;

    /// Get supported language features
    fn supported_features(&self) -> Vec<String>;

    /// Set compiler optimization level
    fn set_optimization_level(&mut self, level: u8) -> Result<(), NyxError>;

    /// Add a compilation pass
    fn add_pass(&mut self, pass: Box<dyn crate::extensions::CompilerPass>) -> Result<(), NyxError>;
}

/// RuntimeAPI - Public runtime interface
///
/// This trait provides the public API for executing compiled code.
/// Implementations provide different runtime environments and execution strategies.
pub trait RuntimeAPI {
    /// Execute bytecode and return a value
    fn execute(&self, bytecode: &Bytecode) -> Result<Value, NyxError>;

    /// Create an isolated sandbox for execution
    fn create_sandbox(&self, config: SandboxConfig) -> Result<Sandbox, NyxError>;

    /// Execute bytecode in a sandbox
    fn execute_in_sandbox(&self, bytecode: &Bytecode, sandbox: &Sandbox) -> Result<Value, NyxError>;

    /// Get runtime capabilities
    fn get_capabilities(&self) -> RuntimeCapabilities;

    /// Set up runtime environment
    fn initialize(&mut self, config: RuntimeConfig) -> Result<(), NyxError>;
}

/// Runtime capabilities
#[derive(Debug, Clone)]
pub struct RuntimeCapabilities {
    /// Supported bytecode versions
    pub supported_versions: Vec<Version>,
    /// Maximum concurrent executions
    pub max_concurrent: usize,
    /// Garbage collection support
    pub gc_support: bool,
    /// JIT compilation support
    pub jit_support: bool,
}

impl Default for RuntimeCapabilities {
    fn default() -> Self {
        Self {
            supported_versions: vec![Version::default()],
            max_concurrent: 4,
            gc_support: true,
            jit_support: false,
        }
    }
}

/// Runtime configuration
#[derive(Debug, Clone)]
pub struct RuntimeConfig {
    /// Enable garbage collection
    pub gc_enabled: bool,
    /// Enable JIT compilation
    pub jit_enabled: bool,
    /// Number of worker threads
    pub worker_threads: usize,
    /// Memory limit in bytes
    pub memory_limit: Option<usize>,
}

impl Default for RuntimeConfig {
    fn default() -> Self {
        Self {
            gc_enabled: true,
            jit_enabled: false,
            worker_threads: 4,
            memory_limit: Some(512 * 1024 * 1024), // 512 MB
        }
    }
}

/// EngineAPI - Engine loading interface
///
/// This trait provides the public API for loading and managing
/// language engines and execution backends.
pub trait EngineAPI {
    /// Load an engine by name
    fn load_engine(&mut self, name: &str) -> Result<EngineHandle, NyxError>;

    /// Unload an engine
    fn unload_engine(&mut self, handle: EngineHandle) -> Result<(), NyxError>;

    /// Get engine capabilities
    fn get_engine_capabilities(&self, handle: EngineHandle) -> Capabilities;

    /// Check if an engine is loaded
    fn is_engine_loaded(&self, name: &str) -> bool;

    /// List available engines
    fn list_engines(&self) -> Vec<String>;

    /// Get engine configuration
    fn get_engine_config(&self, handle: EngineHandle) -> Option<EngineConfig>;
}

/// ModuleAPI - Module loading interface
///
/// This trait provides the public API for loading, managing, and
/// resolving symbols in modules.
pub trait ModuleAPI {
    /// Load a module from the given path
    fn load_module(&self, path: &str) -> Result<ModuleId, NyxError>;

    /// Unload a module
    fn unload_module(&self, id: ModuleId) -> Result<(), NyxError>;

    /// Resolve a symbol in a module
    fn resolve_symbol(&self, module: ModuleId, symbol: &str) -> Result<Symbol, NyxError>;

    /// List all symbols in a module
    fn list_symbols(&self, module: ModuleId) -> Result<Vec<Symbol>, NyxError>;

    /// Get module dependencies
    fn get_dependencies(&self, module: ModuleId) -> Result<Vec<ModuleId>, NyxError>;

    /// Reload a module
    fn reload_module(&self, id: ModuleId) -> Result<ModuleId, NyxError>;
}

// ============================================================================
// Extension Configuration
// ============================================================================

/// Extension configuration loaded from nyx.toml
#[derive(Debug, Clone, Deserialize)]
#[derive(Default)]
pub struct ExtensionConfig {
    /// Engine configurations
    pub engines: Vec<EngineConfig>,
    /// Plugin configurations
    pub plugins: Vec<PluginConfig>,
    /// Standard library paths
    pub stdlib: Vec<String>,
}


/// Plugin configuration
#[derive(Debug, Clone, Deserialize)]
pub struct PluginConfig {
    /// Plugin name
    pub name: String,
    /// Plugin path
    pub path: String,
    /// Plugin version
    pub version: Option<String>,
    /// Enabled state
    pub enabled: bool,
    /// Configuration parameters
    #[serde(default)]
    pub params: HashMap<String, String>,
}

impl PluginConfig {
    /// Create a new plugin config
    pub fn new(name: impl Into<String>, path: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            path: path.into(),
            version: None,
            enabled: true,
            params: HashMap::new(),
        }
    }
}

/// Deserialize trait implementation for ExtensionConfig
use serde::Deserialize;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        let v = Version::default();
        assert_eq!(v.major, 0);
        assert_eq!(v.minor, 1);
        assert_eq!(v.patch, 0);
    }

    #[test]
    fn test_version_parse() {
        let v: Version = "1.2.3".parse().unwrap();
        assert_eq!(v.major, 1);
        assert_eq!(v.minor, 2);
        assert_eq!(v.patch, 3);
    }

    #[test]
    fn test_capabilities_default() {
        let caps = Capabilities::default();
        assert!(!caps.targets.is_empty());
        assert_eq!(caps.max_optimization_level, 3);
    }

    #[test]
    fn test_sandbox_config_default() {
        let config = SandboxConfig::default();
        assert!(config.max_memory.is_some());
        assert!(!config.allow_network);
    }
}
